### ISSUE TITLE
webpack-dev-server is not live reloading bundle.js changes

### ISSUE THREAD

**Issue by nscarlson** [nscarlson/crlsn.io#1]
Stuff is happening, as can be seen in the screenshot below, so it appears that webpack is watching the stuff it needs to.  

The problem is that the changes don't appear live in the browser, even after refreshing

The current npm start script in package.json is the command:

```bash
 webpack-dev-server --inline --hot
```

<img width="863" alt="screen shot 2016-03-29 at 9 09 02 pm" src="https://cloud.githubusercontent.com/assets/3528679/14130787/b1a2a126-f5f2-11e5-9a3e-a0b18c03c58f.png">

@grexecutioner

**Comment by Grexecutioner** [comment]
This should be addressed in commit 9f71f7b66c5d7530be5ab1fede6abfa9cdddf835
